# Generated by Django 5.0.4 on 2025-04-01 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(0, 'Вторичка'), (1, 'Новостройка')], default=0, max_length=20, verbose_name='Тип')),
                ('room_count', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (0, 'Свободная планировка'), (-1, 'Студия')], default=1, verbose_name='Количество комнат')),
                ('house_type', models.CharField(choices=[(1, 'Монолитно-кирпичный'), (2, 'Кирпичный'), (3, 'Монолитный'), (4, 'Панельный'), (5, 'Блочный'), (6, 'Сталинский')], default=1, max_length=20, verbose_name='Тип дома')),
                ('sale_type', models.CharField(choices=[(1, 'Свободная продажа'), (2, 'Альтернатива'), (3, 'Договор уступки права требования'), (4, '214-ФЗ'), (5, 'Предварительный договор купли-продажи')], default=1, max_length=20, verbose_name='Тип продажи')),
                ('mortgage', models.CharField(choices=[(1, 'Да'), (0, 'Нет')], default=0, max_length=10, verbose_name='Ипотека')),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Общая площадь')),
                ('floor', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Этаж')),
                ('total_floors', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Этажность')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота')),
                ('distance_to_center', models.DecimalField(decimal_places=2, help_text='Расстояние в километрах', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Расстояние до центра')),
            ],
            options={
                'verbose_name': 'Недвижимость',
                'verbose_name_plural': 'Объекты недвижимости',
            },
        ),
    ]
