# Generated by Django 5.0.4 on 2025-04-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='house_type',
            field=models.CharField(choices=[('1', 'Монолитно-кирпичный'), ('2', 'Кирпичный'), ('3', 'Монолитный'), ('4', 'Панельный'), ('5', 'Блочный'), ('6', 'Сталинский')], default=1, max_length=20, verbose_name='Тип дома'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='mortgage',
            field=models.CharField(choices=[('1', 'Есть'), ('0', 'Нет')], default=0, max_length=10, verbose_name='Ипотека'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='room_count',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (0, 'Свободная планировка'), (-1, 'Студия')], default=1, verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='sale_type',
            field=models.CharField(choices=[('1', 'Свободная продажа'), ('2', 'Альтернатива'), ('3', 'Договор уступки права требования'), ('4', '214-ФЗ'), ('5', 'Предварительный договор купли-продажи')], default=1, max_length=20, verbose_name='Тип продажи'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='type',
            field=models.CharField(choices=[('0', 'Вторичка'), ('1', 'Новостройка')], default=0, max_length=20, verbose_name='Тип'),
        ),
    ]
