# Generated by Django 5.0.4 on 2025-04-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_realestate_house_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='mortgage',
        ),
        migrations.AddField(
            model_name='realestate',
            name='district',
            field=models.CharField(choices=[('Центральный мкр', 'Центральный мкр'), ('Черемушки мкр', 'Черемушки мкр'), ('Завод Измерительных Приборов мкр', 'Завод Измерительных Приборов мкр'), ('Дубинка мкр', 'Дубинка мкр'), ('Табачная Фабрика мкр', 'Табачная Фабрика мкр')], default='Центральный мкр', max_length=50, verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='street',
            field=models.CharField(choices=[('Прочие', 'Прочие'), ('улица Промышленная', 'улица Промышленная'), ('улица Стасова', 'улица Стасова'), ('Кубанская улица', 'Кубанская улица'), ('Старокубанская улица', 'Старокубанская улица'), ('Красная улица', 'Красная улица'), ('улица Коммунаров', 'улица Коммунаров'), ('улица Вишняковой', 'улица Вишняковой'), ('Колхозная улица', 'Колхозная улица'), ('Воронежская улица', 'Воронежская улица'), ('Обрывная улица', 'Обрывная улица'), ('Ставропольская улица', 'Ставропольская улица'), ('улица Железнодорожная', 'улица Железнодорожная'), ('Московская улица', 'Московская улица'), ('улица Митрофана Седина', 'улица Митрофана Седина'), ('Садовая улица', 'Садовая улица')], default='Прочие', max_length=50, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='distance_to_center',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Расстояние в километрах (рассчитывается автоматически)', max_digits=6, null=True, verbose_name='Расстояние до центра'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='house_type',
            field=models.CharField(choices=[('Панельный', 'Панельный'), ('Монолитно-кирпичный', 'Монолитно-кирпичный'), ('Кирпичный', 'Кирпичный'), ('Монолитный', 'Монолитный'), ('Блочный', 'Блочный'), ('Сталинский', 'Сталинский')], default='Панельный', max_length=50, verbose_name='Тип дома'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='room_count',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (0, 'Свободная планировка'), (-1, 'Студия'), (4, '4'), (5, '5'), (6, '6')], default=1, verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='sale_type',
            field=models.CharField(choices=[('Свободная продажа', 'Свободная продажа'), ('Альтернатива', 'Альтернатива'), ('Договор уступки права требования', 'Договор уступки права требования'), ('214-ФЗ', '214-ФЗ'), ('Предварительный договор купли-продажи', 'Предварительный договор купли-продажи')], default='Свободная продажа', max_length=50, verbose_name='Тип продажи'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='type',
            field=models.IntegerField(choices=[(0, 'Вторичное жильё'), (1, 'Новостройка')], default=0, verbose_name='Тип'),
        ),
    ]
